///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApiErrorException {
/*
{
  "error": true,
  "message": "Cannot read property '1' of undefined"
}
*/

  bool? error;
  String? message;

  ApiErrorException({
    this.error,
    this.message,
  });
  ApiErrorException.fromJson(Map<String, dynamic> json) {
    error = json["error"];
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["error"] = error;
    data["message"] = message;
    return data;
  }
}
